site_name: GarudaNvim

site_url: https://garudanvim.github.io

theme:
  name: material
  logo: assets/logowbg.png
  favicon: images/favicon32.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to light mode
      primary: teal
      accent: purple 
    - scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode    
      primary: teal
      accent: lime

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GarudaNvim

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/GarudaNvim"  target="_blank" rel="noopener">GarudaNvim</a>
