# Project Information
site_name: GarudaNvim
site_url: https://garudanvim.github.io
site_author: Priyanshu Ranjan

# Configuration
theme:
  name: material
  logo: assets/images/logo-dark.png
  favicon: assets/images/favicon.png
  icon:
    repo: simple/github
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate # dark theme
      toggle:
        icon: material/weather-sunny 
        name: Switch to light mode
      primary: black
      accent: amber
    - scheme: default # light theme
      toggle:
        icon: material/weather-night
        name: Switch to dark mode    
      primary: indigo
      accent: deep orange

# Navigation
nav:  
  - Home: index.md
  - Installation: installation.md
  - Features: features.md
  - Plugins: plugins.md
  - Keymaps: keymaps.md
  - Which-Key: whichkey.md
  - Themes: themes.md

# Add GitHub link to the navbar
repo_url: https://github.com/GarudaNvim
repo_name: GitHub

# Plugins
plugins:
  - search

extra_css:
  - assets/css/fonts.css
  - assets/css/nav_link.css

# Social and Metadata Information
extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://github.com/GarudaNvim/GarudaNvim.github.io
      name: Website Github
  metadata:
      description: A minimal and powerful Neovim configuration for macOS and Linux.
      keywords: Neovim, GarudaNvim, macOS, Linux, configuration, coding

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Copyright
copyright: |
  &copy; 2024 <a href="https://github.com/GarudaNvim"  target="_blank" rel="noopener">GarudaNvim</a>
