# Project Information
site_name: GarudaNvim
site_url: https://garudanvim.github.io
site_author: Priyanshu Ranjan

# Configuration
theme:
  name: material
  logo: assets/images/logo-dark.png
  favicon: assets/images/favicon.png
  icon:
    repo: simple/github
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to light mode
      primary: black  # Softer, less harsh primary color
      accent: amber  # A warmer accent for better contrast
      background: '#121212'  # Darker background
      surface: '#1E1E1E'  # Slightly lighter surface to differentiate sections
      on-primary: 'white'  # Text color on primary elements
      on-surface: 'white'  # Text color on general surfaces
    - scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode    
      accent: orange

# Navigation
nav:  
  - Home: index.md
  - Installation: installation.md
  - Features: features.md
  - Plugins: plugins.md
  - Keymaps: keymaps.md
  - Which-Key: whichkey.md
  - Themes: themes.md

# Add GitHub link to the navbar
repo_url: https://github.com/GarudaNvim
repo_name: GitHub

# Plugins
plugins:
  - search

extra_css:
  - assets/css/extra.css

# Social and Metadata Information
extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://github.com/GarudaNvim/GarudaNvim.github.io
      name: Website Github
  metadata:
      description: A minimal and powerful Neovim configuration for macOS and Linux.
      keywords: Neovim, GarudaNvim, macOS, Linux, configuration, coding

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Copyright
copyright: |
  &copy; 2024 <a href="https://github.com/GarudaNvim"  target="_blank" rel="noopener">GarudaNvim</a>
